### PR TITLE
Resample disk labels

### LINKED ISSUE #74: Error: resampling of disk labels fails
In last results certain subjects (notably sub-brnoUhb*) have disk-labels with non-int values. Example:  [sub-brnoUhb02_T2w_labels-disc-manual_RPI_r.zip](https://github.com/sct-pipeline/csa-atrophy/files/5184061/sub-brnoUhb02_T2w_labels-disc-manual_RPI_r.zip)
The function `sct_resample` uses by default a linear resampling that is not adequate for these labels. A solution is to use an interpolation to nn (nearest neighbour).  However, labels seem to be missing on output images.

**test:**
command: `sct_resample -i sub-brnoUhb02_T2w_labels-disc-manual.nii.gz -mm 0.8x0.8x0.8 -x nn -o test.nii.gz`
file: [sub-brnoUhb02_T2w_labels-disc-manual.zip](https://github.com/sct-pipeline/csa-atrophy/files/5184057/sub-brnoUhb02_T2w_labels-disc-manual.zip)
result image: [test.zip](https://github.com/sct-pipeline/csa-atrophy/files/5184071/test.zip)

### PR DESCRIPTION
**Pull request by PaulBautin**
In last results certain subjects (notably sub-brnoUhb*) had disk-labels with non-int values because `sct_resample` uses by default a linear resampling that is not adequate for these labels. A solution is to use a nn (nearest neighbour) interpolation.

result: [sub-brnoUhb02_T2w_RPI_r_labels-disc.zip](https://github.com/sct-pipeline/csa-atrophy/files/5184726/sub-brnoUhb02_T2w_RPI_r_labels-disc.zip)

DONE: 
- dilate disk labels with `sct_maths -dilate 3` 
- resample disk labels

FIXES #74

### CODE REVIEW

File: process_data.sh [hunk 1]
```diff
@@ -54,22 +50,23 @@ label_if_does_not_exist(){
...
+  FILELABEL="${file}_labels-disc.nii.gz"
+  FILELABELMANUAL="${path_derivatives}/${SUBJECT}_${contrast_str}_labels-disc-manual"
+  if [ -e "${FILELABELMANUAL}.nii.gz" ]; then
     echo "manual labeled file was found: ${FILELABELMANUAL}"
     # reorienting and resampling image
-    sct_image -i ${FILELABELMANUAL} -setorient RPI -o "${path_derivatives}/${SUBJECT}_${contrast_str}_RPI_labels-disc-manual.nii.gz"
-    sct_resample -i ${FILELABELMANUAL} -mm $interp -o "${path_derivatives}/${SUBJECT}_${contrast_str}_RPI_r_labels-disc-manual.nii.gz"
-    rsync -avzh "${path_derivatives}/${SUBJECT}_${contrast_str}_RPI_r_labels-disc-manual.nii.gz" ${FILELABEL}
+    sct_image -i ${FILELABELMANUAL}.nii.gz -setorient RPI -o "${FILELABELMANUAL}_RPI.nii.gz"
+    sct_maths -i ${FILELABELMANUAL}_RPI.nii.gz -dilate 3 -type uint8 -o ${FILELABELMANUAL}_RPI_dil.nii.gz
```
Comment (jcohenadad) [inline process_data.sh:59]: check if dilate 3 is not too large (uses default size=ball), dilate =3 means radius of 3, so diameter ~6 vox-- if you have two labels that are 10vox apart, there will be an overlap-- maybe dilate=1 is reasonable-- do some thorough checks and document--

File: process_data.sh [hunk 2]
```diff
@@ -54,22 +50,23 @@ label_if_does_not_exist(){
...
     # Generate labeled segmentation
-    sct_label_vertebrae -i ${file}.nii.gz -s ${file_seg}.nii.gz -c ${contrast} -discfile ${FILELABELMANUAL} -qc ${PATH_QC} -qc-subject ${SUBJECT}
+    sct_label_vertebrae -i ${file}.nii.gz -s ${file_seg}.nii.gz -c ${contrast} -discfile "${FILELABELMANUAL}_RPI_dil_r.nii.gz" -qc ${PATH_QC} -qc-subject ${SUBJECT}
   else
     # Generate labeled segmentation
     sct_label_vertebrae -i ${file}.nii.gz -s ${file_seg}.nii.gz -c ${contrast} -qc ${PATH_QC} -qc-subject ${SUBJECT}
   fi
   # Create labels in the Spinal Cord
-  sct_label_utils -i ${file_seg}_labeled.nii.gz -vert-body 0 -o ${FILELABEL}.nii.gz
+  sct_label_utils -i ${file_seg}_labeled.nii.gz -vert-body 0 -o ${FILELABEL}
```
Comment (jcohenadad) [inline process_data.sh:69]: this is a change of convention-- it confuses when reading the code-- pls justify why you made this change

File: process_data.sh (hunk 1 above)
Comment (PaulBautin) [reply process_data.sh:59]: I checked different dilatation and here is the growth process:
Screenshot from 2020-09-07 19-21-05

With dilatation 1, labelling still has errors. I have noticed no errors for dilate = 2, it seems like a reasonable choice without the increase of radius of 3 and 4.

File: process_data.sh (hunk 2 above)
Comment (PaulBautin) [reply process_data.sh]: Sorry for the confusion, i went back to general convention in commit https://github.com/sct-pipeline/csa-atrophy/pull/75/commits/ec50e0bbc5ca3ca3b8303ca6bd850bb7e060996a

File: process_data.sh (hunk 1 above)
Comment (jcohenadad) [reply process_data.sh]: great investigation @PaulBautin 🏅

**Comment by PaulBautin** [comment]
@jcohenadad, is this PR ready to be merged?

**Review by jcohenadad — APPROVED** [review]
