### PR TITLE
Minor refactoring of process_data.sh

### LINKED ISSUE #47: error labelling
@jcohenadad, C2-C3 automatic detection fails for about 4 out of 20 subjects and labelling is off for 4 out of 5 subjects in QC. Should i test another dilation factor?

Current process:
~~~
# dilate segmentation (for cropping)
sct_maths -i ${file_seg}.nii.gz -dilate 15 -shape cube -o ${file_seg}_dil.nii.gz
# crop image
sct_crop_image -i ${file}.nii.gz -m `${file_seg}_dil.nii.gz`
~~~

QC:
sub-cardiff05_T1w_RPIr_crop
sub-unf03_T1w_RPIr_crop

### LINKED ISSUE #48: FileNotFoundError: cannot find yml file
When running on compute canada:
~~~
+ for i_transfo in '${seq_transfo[@]}'
+ affine_transfo -i sub-vuiisIngenia06_T1w_RPIr_crop_r1.nii.gz -transfo /scratch/jcohen/results_csa_t1_20200818/results/transfo_values.csv -config /scratch/jcohen/results_csa_t1_20200818/results/sub-vuiisIngenia06//home/jcohen/csa-atrophy/config_script_t1.yml -o _t1
/scratch/jcohen/results_csa_t1_20200818/results/sub-vuiisIngenia06//home/jcohen/csa-atrophy/config_script_t1.yml
Traceback (most recent call last):
  File "/home/jcohen/.local/bin/affine_transfo", line 11, in <module>
    load_entry_point('csa-atrophy', 'console_scripts', 'affine_transfo')()
  File "/home/jcohen/csa-atrophy/affine_transfo.py", line 219, in main
    config_param = yaml_parser(path_config_file)
  File "/home/jcohen/csa-atrophy/affine_transfo.py", line 82, in yaml_parser
    with open(config_file, 'r') as config_var:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/jcohen/results_csa_t1_20200818/results/sub-vuiisIngenia06//home/jcohen/csa-atrophy/config_script_t1.yml'
~~~

this concatenation of path is the culprit: `'/scratch/jcohen/results_csa_t1_20200818/results/sub-vuiisIngenia06//home/jcohen/csa-atrophy/config_script_t1.yml'`

it should be easy to fix

### PR DESCRIPTION
**Pull request by PaulBautin**
DONE:
- improve variable naming in process_data.sh
- change resampling suffix ${file}r to ${file}_r to have same filename as in dataset derivatives
- remove config_script from PATH_RESULTS #48

FIX #47 , FIX #48

### CODE REVIEW

File: process_data.sh [hunk 1]
```diff
@@ -110,41 +110,41 @@ cd anat
...
+  file=${SUBJECT}_${contrast_str}
   # Reorient to RPI
-  sct_image -i ${file_c}.nii.gz -setorient RPI -o ${file_c}_RPI.nii.gz
-  file_c_o=${file_c}_RPI
+  sct_image -i ${file}.nii.gz -setorient RPI -o ${file}_RPI.nii.gz
+  file=${file}_RPI
   # Resample to 0.8mm iso
-  sct_resample -i ${file_c}_RPI.nii.gz -mm 0.8x0.8x0.8 -o ${file_c_o}r.nii.gz
-  file_c_or=${file_c_o}r
+  sct_resample -i ${file}.nii.gz -mm 0.8x0.8x0.8 -o ${file}r.nii.gz
```
Comment (jcohenadad) [inline process_data.sh:118]: or you can create a variable for the interpolation value and bring the code outside the if case. e.g.
~~~
if [ $contrast == "t2" ]; then
  contrast_str="T2w"
  interp="0.8x0.8x0.8"
elif [ $contrast == "t1" ]; then
  contrast_str="T1w"
  interp="1x1x1"
fi
file=${SUBJECT}_${contrast_str}
# Reorient to RPI
sct_image -i ${file}.nii.gz -setorient RPI -o ${file}_RPI.nii.gz
# Resample
sct_resample -i ${file}.nii.gz -mm $interp -o ${file}r.nii.gz
~~~

Comment (PaulBautin) [reply process_data.sh]: Much cleaner! implemented in https://github.com/sct-pipeline/csa-atrophy/pull/46/commits/f1f62ce655a7df6a34e059ea36c81410ffc87883

**Comment by PaulBautin** [comment]
@jcohenadad. PR is ready for review.
